# Generated by Django 5.0.2 on 2025-05-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_chapter_chapter_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['level', 'chapter_number']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='order',
        ),
    ]
