# Generated by Django 5.0.2 on 2025-05-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('book_name', 'chapter_number')},
        ),
    ]
