# Generated by Django 5.0.2 on 2025-06-12 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_alter_chapter_chapter_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammarpattern',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='title',
        ),
        migrations.RemoveField(
            model_name='grammarpattern',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='grammarpattern',
            name='explanation',
        ),
        migrations.AddField(
            model_name='grammarpattern',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='example_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='GrammarUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('explanation', models.TextField()),
                ('examples', models.JSONField(default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='chapters.grammarpattern')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KanjiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('radical', models.CharField(blank=True, max_length=10)),
                ('on_yomi', models.CharField(blank=True, max_length=100)),
                ('kun_yomi', models.CharField(blank=True, max_length=100)),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_info', to='chapters.vocabulary')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
