# Generated by Django 5.0.2 on 2025-06-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_alter_grammarpattern_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammarusage',
            name='examples',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='GrammarExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence', models.TextField()),
                ('translation', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='chapters.grammarusage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
