# Generated by Django 5.0.2 on 2025-05-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_inputtestquestion_inputtestattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtestquestion',
            name='book_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inputtestquestion',
            name='chapter_number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
